#!/usr/bin/env python3
"""Internal-link gate for the built site. Deterministic, offline, cross-platform.

Checks every href/src in built HTML against the actual files in the dist tree,
CASE-SENSITIVELY (GitHub Pages serves from Linux; Windows dev boxes lie about
case). External links are out of scope here (external rot is tracked by the
audit crawler, not the build gate).

Usage:
  python3 scripts/check-links.py site/dist --scope astro [--base /repo-subpath]
  python3 scripts/check-links.py site/dist --scope all

  --scope astro : only HTML files generated by Astro (generator meta marker) —
                  the pages the new site owns; the HARD per-wave gate.
  --scope all   : every HTML file incl. legacy overlay — burn-down visibility.
  --base        : base path prefix used at build time (staging subpath); it is
                  stripped from root-absolute links before resolution.

Exits 1 on: zero files scanned (a silent no-op gate is a failure), or any
broken internal link.
"""
import argparse
import os
import posixpath
import re
import sys

ap = argparse.ArgumentParser()
ap.add_argument("root")
ap.add_argument("--scope", choices=["astro", "all"], default="astro")
ap.add_argument("--base", default="/")
args = ap.parse_args()

ROOT = os.path.abspath(args.root)
BASE = "/" + args.base.strip("/")  # "/" or "/dsrl-site-staging"
ASTRO_MARKER = 'name="generator" content="Astro'
LINK_RE = re.compile(r"""(?:href|src)\s*=\s*["']([^"']+)["']""", re.I)
SKIP_PREFIX = ("http://", "https://", "mailto:", "tel:", "javascript:", "data:", "#", "//")

# Exact-case file inventory (posix-style relative paths).
inventory = set()
for dirpath, _dirnames, filenames in os.walk(ROOT):
    rel = os.path.relpath(dirpath, ROOT)
    for fn in filenames:
        p = fn if rel == "." else f"{rel}/{fn}"
        inventory.add(p.replace(os.sep, "/").replace("\\", "/"))

html_files = sorted(f for f in inventory if f.lower().endswith((".html", ".htm")))
if args.scope == "astro":
    scoped = []
    for f in html_files:
        try:
            with open(os.path.join(ROOT, f), encoding="utf-8", errors="replace") as fh:
                if ASTRO_MARKER in fh.read(4096):
                    scoped.append(f)
        except OSError:
            pass
    html_files = scoped

if not html_files:
    print(f"check-links: FAIL — zero HTML files in scope '{args.scope}' under {ROOT}")
    sys.exit(1)

broken = []
checked = 0
for f in html_files:
    text = open(os.path.join(ROOT, f), encoding="utf-8", errors="replace").read()
    fdir = posixpath.dirname(f)
    for m in LINK_RE.finditer(text):
        raw = m.group(1).strip()
        if not raw or raw.startswith(SKIP_PREFIX):
            continue
        target = raw.split("#")[0].split("?")[0]
        if not target:
            continue
        if target.startswith("/"):
            if BASE != "/" and (target == BASE or target.startswith(BASE + "/")):
                target = target[len(BASE):] or "/"
            resolved = posixpath.normpath(target.lstrip("/"))
        else:
            resolved = posixpath.normpath(posixpath.join(fdir, target))
        checked += 1
        if resolved in (".", ""):
            resolved = "index.html"
        candidates = {resolved, resolved.rstrip("/") + "/index.html"}
        if not any(c in inventory for c in candidates):
            broken.append((f, raw, resolved))

print(f"check-links: scope={args.scope} files={len(html_files)} links-checked={checked} broken={len(broken)}")
for f, raw, resolved in broken[:120]:
    print(f"  BROKEN {f}: {raw}  ->  {resolved}")
if len(broken) > 120:
    print(f"  ... and {len(broken) - 120} more")
sys.exit(1 if broken else 0)
